ScrollReveal({
    origin: 'top',
    distance: '30px',
    duration: 700
  }).reveal(`
    .box-top,
    .box-bottom,
    .top-header,
    .bottom-header,
    .container select,
    .form-container h2,
    .form-container hr,
    .form-container label,
    .form-container input,
    .form-container textarea,
    .form-link-login,
    .form-link,
    .form-footer,
    button.en,
    button.ca,
    a.en,
    .resources button,
    .resources .button-theme,
    .navbar,
    main section h1,
    main section h2,
    main section h3,
    main section,
    main section a,
    footer .footer-col,
    footer .button-top,
    main .container, 
    main .campo-vagas,
    main .campo-curso,
    main .campo-noticias,
    .enabled`)
